### ISSUE TITLE
Compose query via UI to search Spacetime

### ISSUE THREAD

**Issue by sdgandhi** [polybase/explorer#9]
This will be interesting for non technical users to look for interesting things. 

We could bootstrap with a few open datasets.

**Comment by calummoore** [comment]
Not sure I understand what you mean? Like search of Spacetime data - we don't currently offer a search API so that would be challenging.

**Comment by sdgandhi** [comment]
I was thinking about the filter type queries we have:

```js
const docs = await collectionReference.where("country", "==", "UK").get()
```

This would make the explorer similar to other block explorers where you can actually explore the data.
